### ISSUE TITLE
视频全屏后还原出现问题

### ISSUE THREAD

**Issue by github5211** [syhyz1990/darkmode#19]
我发现在观看YouTube的视频时候，没有开启夜间模式，当视频全屏后再退出就会自动变成夜间模式，但是插件切换图标还是没有变。希望下个版本能解决这个问题，谢谢

**Comment by syhyz1990** [comment]
感谢反馈，2.0.3版本已修复，[点击更新](https://www.baiduyun.wiki/tool/install-darkmode.html)。

**Comment by syhyz1990** [comment]
> 我发现在观看YouTube的视频时候，没有开启夜间模式，当视频全屏后再退出就会自动变成夜间模式，但是插件切换图标还是没有变。希望下个版本能解决这个问题，谢谢

@maboloshi 感谢反馈，2.0.3版本已修复，[点击更新](https://www.baiduyun.wiki/tool/install-darkmode.html)。
