### ISSUE TITLE
黑夜模式助手油猴疑似会造成百度搜索页面频繁刷新

### ISSUE THREAD

**Issue by TvT-ME** [syhyz1990/darkmode#22]
开启黑夜模式助手油猴后，在百度搜索后，一往下滑，就会刷新页面。经测试，把脚本关了，就没有这样的情况产生，我安装了很多脚本，可能脚本之间存在冲突问题

**Comment by syhyz1990** [comment]
百度搜索每次点击搜索会清空脚本样式，做了特殊兼容，不刷新的话夜间模式会失效。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月15日(周六) 中午12:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/darkmode] 黑夜模式助手油猴疑似会造成百度搜索页面频繁刷新 (Issue #22)




 
开启黑夜模式助手油猴后，在百度搜索后，一往下滑，就会刷新页面。经测试，把脚本关了，就没有这样的情况产生，我安装了很多脚本，可能脚本之间存在冲突问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TvT-ME** [comment]
了解了，感谢大佬解答

**Comment by syhyz1990** [comment]
@TvT-ME 升级到v2.1.0 此问题已经完美解决，不用刷新了。
