### ISSUE TITLE
建议可自定义按钮位置

### ISSUE THREAD

**Issue by wha4up** [syhyz1990/darkmode#23]
现在的位置比较尴尬，会挡住部分站点诸如”回到顶部“之类的按钮，比如本脚本官方网站……

**Comment by syhyz1990** [comment]
可以自行修改代码208到209行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月24日(周一) 下午2:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/darkmode] 建议可自定义按钮位置 (Issue #23)




 
现在的位置比较尴尬，会挡住部分站点诸如”回到顶部“之类的按钮，比如本脚本官方网站……
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
