### ISSUE TITLE
部分论坛会直接黑屏

### ISSUE THREAD

**Issue by YunheXu** [syhyz1990/darkmode#3]
例如：https://www.pgfans.cn/

**Comment by YunheXu** [comment]
https://hrtsea.com/29882.html 这个也是

**Comment by syhyz1990** [comment]
升级到1.0.2 可以添加到白名单里 ,

**Comment by syhyz1990** [comment]
添加到排除列表里



---原始邮件---
发件人: "Yunhe Xu"<notifications@github.com&gt;
发送时间: 2020年3月30日(周一) 晚上6:51
收件人: "syhyz1990/darkmode"<darkmode@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"iPc"<syhyz1990@qq.com&gt;;
主题: Re: [syhyz1990/darkmode] 部分论坛会直接黑屏 (#3)




 
Closed #3.
