### ISSUE TITLE
好像在暴力猴里没有切换按钮

### ISSUE THREAD

**Issue by weavers1f** [syhyz1990/darkmode#4]
之前用油猴插件的时候是正常的，但是现在好像在暴力猴里没有切换按钮。开关里一开就全部页面都暗黑模式，一关就全部关。[https://imgkr.cn-bj.ufileos.com/a2e6dc80-b217-421f-898f-0694ac3132eb.png](url)

**Comment by chermy** [comment]
开关下面应该有一个该站点禁用才对, 不知道为啥你没有. 另外点代码图标可以设置exclude 规则, 就是有点麻烦
