### ISSUE TITLE
能否做到只针对某个网页生效其他网页不生效呢

### ISSUE THREAD

**Issue by xtxt19931207** [syhyz1990/darkmode#9]
现在好像只能添加黑名单，不能添加白名单

**Comment by syhyz1990** [comment]
可以，在脚本前面添加@match 你要生效的网址



---原始邮件---
发件人: "xtxt19931207"<notifications@github.com&gt;
发送时间: 2020年7月18日(周六) 上午8:34
收件人: "syhyz1990/darkmode"<darkmode@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/darkmode] 能否做到只针对某个网页生效其他网页不生效呢 (#9)




 
现在好像只能添加黑名单，不能添加白名单

**Comment by xtxt19931207** [comment]
非常感谢回复，这样确实可以，请问如果我要添加多个网站可以用什么格式将网站添加进去呢？

iPc <notifications@github.com> 于2020年7月18日周六 上午9:33写道：
